source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '~> 1.16.2'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '~> 1.27.0'
gem 'concurrent-ruby', '< 1.3.4'
gem 'cocoapods-repo-update'
gem 'cocoapods-user-defined-build-types'


# Ruby 3.4.0 has removed some libraries from the standard library.
# https://github.com/fastlane/fastlane/issues/21942#issuecomment-2582202838
gem 'abbrev'
gem 'logger'
gem 'mutex_m'
gem 'csv'
gem 'bigdecimal'
gem 'benchmark'
